server:
  port: 8080
  servlet:
    context-path: /potato-api

spring:
  application:
    name: potato-api
  datasource:
    url: "jdbc:mysql://localhost:3307/potato"
    username: root
    password: 171104
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "potatoapp.adm1n@gmail.com"
    password: "usvidloymphbjdci"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: "dcudlkqcm"
  api_key: "734251979716821"
  api_secret: "WHzx_91QpnZwhLi0DOrxJGMJDT4"

app:
  server-url: "http://localhost:8080"